### ISSUE TITLE
Update API to spdlog v1.x

### ISSUE THREAD

**Issue by noc0lour** [bodgergely/spdlog-python#10]
Are you interested in supporting splod v1.x? Currently the code only works with previous versions. 

I have a branch in my fork https://github.com/noc0lour/spdlog-python/tree/update_to_v1x which is doing that, but needs some cleanup probably.

**Comment by gabime** [comment]
I am very interested.

**Comment by rafalmiel** [comment]
+1

**Comment by bodgergely** [comment]
I will try and upgrade spdlog-python to work with v1.x.
Once done a new python pip package will be released too.
@noc0lour I will take a look at your branch and see what else might need to be done.
@rafalmiel Your help is also appreciated if you don't have much "on your plate".

**Comment by noc0lour** [comment]
@bodgergely looking at my commit I had auto-formatting on save enabled. I'll sort out the changes in a separate patchset and post a pull-request.

**Comment by severinstrobl** [comment]
I just started looking into this, as we are also interested in getting support for more recent versions of spdlog. Most of the changes are straightforward, with the exception of the async support. In the current implementation, the async flag is global for all loggers, but can be changed later on. With the changes to spdlog in versions 1.x, `spd::async_logger` has to be instantiated explicitly in case async logging is desired. For me the question is, whether async logging should be controlled via a global flag or for each logger individually. Personally, I would prefer the second option, but this breaks the current API. I'll try to post a pull-request later today.
@bodgergely Do you have any preference regarding the future async support?

**Comment by bodgergely** [comment]
I accepted @severinstrobl PR and released spodlog-python v2.0.0.
I also agreed that the async flag per logger instance is a cleaner way to do it even if we sacrifice the backwards compatibility.
