### ISSUE TITLE
Expose underlying spdlog instance

### ISSUE THREAD

**Issue by severinstrobl** [bodgergely/spdlog-python#13]
We are working on a project coupling multiple C++ libraries (wrapped into different Python modules using pybind11) via a single Python script. On the Python end, spdlog-python fits our needs perfectly, but for the wrapped C++ libraries we face a problem: We would like to use the same instance of the underlying spdlog instance both on the Python side and from within the C++ code. This would allow the consistent logging across different modules/libraries, controlled by the Python code. It should be enough to expose the spdlog instance via the spdlog-python API, without the need to provide full bindings to spdlog itself. I'll open a pull request which allows us to do the following:
```python
import spdlog as spd
logger = spd.FileLogger('shared_logger', '/tmp/spdlog_example.log')
logger.set_level(spd.LogLevel.DEBUG);

logger.info("Hello from Python!")

import test # Dummy C++ library
test.set_logger(logger.get_underlying_logger())
test.foo(42)
```

The C++ dummy library wrapped via pybind11 would look something like this:
```cpp
#include <pybind11/pybind11.h>
#include <spdlog/spdlog.h>

std::shared_ptr<spdlog::logger> logger;

void setLogger(std::shared_ptr<spdlog::logger> l) {
    logger = std::move(l);
}

void foo(int i) {
    logger->warn("Hello from C++: {}", i);
}

PYBIND11_MODULE(test, m)
{
    m.def("set_logger", setLogger);
    m.def("foo", foo);
}
```

There might be a better way to achieve this, I'm more than happy to experiment some more in case you have any suggestions.

**Comment by bodgergely** [comment]
Thanks for this idea and the PR. Happy to help with your use case. I will look at it this week.

**Comment by roastduck** [comment]
Hi, I know this thread is old and has been closed for a while, but I have some new questions on using spdlog both from the Python side and the C++ side simultaneously.

I see spdlog has a global [Logger Registry](https://github.com/gabime/spdlog/wiki/5.-Logger-registry), which can be used to get a logger instance by name from anywhere in the program. Is it supported in spdlog-python? If I register a logger instance from the Python side, can it be looked up in the C++ side? If this is possible, then I don't have to pass logger instances explicitly from modules, and this can be helpful if I have multiple logger instances.
