### ISSUE TITLE
Release of v2.0.0 on pypi.org

### ISSUE THREAD

**Issue by severinstrobl** [bodgergely/spdlog-python#16]
Thanks for tagging the updated version. Are there plans to push the new release to pypi.org as well? This would simplify the installation via pip.

**Comment by bodgergely** [comment]
@severinstrobl Sure, I was thinking about it, just procrastinated so far, so thank for the push :)

**Comment by bodgergely** [comment]
@severinstrobl Done. You can try to see if it works on your end. (I can only upload the source to pypi and the wheel gets always built on the client machine. Works on my machine (linux))
