### ISSUE TITLE
pip wrongly installs headers and C files at base of install directory

### ISSUE THREAD

**Issue by mdorier** [bodgergely/spdlog-python#20]
When I clone this repo and do `python setup.py install --user`, everything is fine. I end up with spdlog installed in my `~/.local` directory. No headers are installed, the packages in properly located in `~/.local/lib/python3.6/site-packages`. This is the expected behavior, and it's what I get with the current HEAD and with the tag v2.0.0.

If I install spdlog with pip, however, while the package itself (.py and .so files) is properly installed in `~/.local/lib/python3.6/site-packages`, I however see also all the .h, .hpp, and .cpp files of spdlog copied in `~/.local` (at its base). Those file are useless and have no place there.

**Comment by ka-bo** [comment]
Hi, the merge request #17 should fix this. And actually, I think it did. That is why installing from your local directory, i.e. the code checked out here works just fine.

As far as I remember, the version number did not get changed with this merge. Whether for this reason or any other: The version on pypi, which gets fetched by pip, does not contain the fix at the moment.

**Comment by bodgergely** [comment]
@ka-bo I just created a new version and uploaded a new 2.0.1 version to pypi. However the packaged up sdist (created via `python3 setup.py sdist`) does not include now the headers to spdlog and fails during compilation for the user.
Can you take a look to confirm?

**Comment by ka-bo** [comment]
I can confirm that it did not work correctly for the sdist. I tried to fix it, please test it.

**Comment by bodgergely** [comment]
Thanks @ka-bo great fix! I have released version 2.0.2 to pypi.
