### ISSUE TITLE
Default logger and question about implementation

### ISSUE THREAD

**Issue by adriendelsalle** [bodgergely/spdlog-python#22]
Hi @bodgergely !
Thanks for your work!

I would like to take advantage of your experience with `pybind11` and `spdlog` to understand why you had to rewrite `level_enum` or `logger` classes instead of using the `spdlog` ones by *simply* wrapping them. I also noticed you didn't exposed a default logger.

I'm facing troubles when wrapping a simple code using default logger with `pybind11`. For example:

**wrapping.cc**
```c++
...
log.def("set_level", &spdlog::set_level);
```
compiles but has no effect on the logger.
But the following implementation works:
**example.h**
```c++
#ifndef EXAMPLE
#define EXAMPLE

#include <spdlog/spdlog.h>

void set_level(spdlog::level::level_enum level);

#endif
```
**example.cc**
```c++
#include "example.h"
void set_level(spdlog::level::level_enum level)
{
  spdlog::set_level(level);
}
```
**wrapping.cc**
```c++
...
log.def("set_level", &set_level);
```

I'm not able to understand why. Could you please help? Is it related to your reimplementation of some base objects and the missing default logger?

I'm a C++ beginner, don't hesitate if you need a more detailed snippet to get the case.

Thanks!

**Comment by bodgergely** [comment]
Thanks for your kind words :) My memory is a bit rusty on this project, let me go over the source code and will get back to you with some possible answers.

**Comment by adriendelsalle** [comment]
Hi @bodgergely 

I understood that I'm in a similar situation than [How to use spdlog in DLLs](https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs).
So I implemented some proxy functions to get the logger and change its level from the wrapping side. This is basically all I need to do in my case, the rest is done by the C++ code.

Thanks for your reply and don't hesitate to comment if you have time for that.
