### ISSUE TITLE
Cannot install via PyPI or Github

### ISSUE THREAD

**Issue by RonaldoAPSD** [bodgergely/spdlog-python#25]
For some reason when ever I try to install spdlog, I keep getting this error. I've tried installing as an admin via PyPI. I've tried installing it as a submodule then installing it but I get the same error. I've tried using wheel and I still get the same error. I'm not sure if its just me or if there is something wrong with the setup.py file. 

I've written the error below, I'm trying to figure out why I'm getting the error but I just cant seem to figure it out. 

`Collecting spdlog
  Using cached spdlog-2.0.2.tar.gz (113 kB)
Collecting pybind11>=2.2
  Using cached pybind11-2.6.2-py2.py3-none-any.whl (191 kB)
Using legacy 'setup.py install' for spdlog, since package 'wheel' is not installed.
Installing collected packages: pybind11, spdlog
    Running setup.py install for spdlog: started
    Running setup.py install for spdlog: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'D:\ViperGL\ViperGL\ViperGLEnv\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ronal\\AppData\\Local\\Temp\\pip-install-ruvcf595\\spdlog_c72a425b30be4082819d3d73c1eddb44\\setup.py'"'"'; __file__='"'"'C:\\Users\\ronal\\AppData\\Local\\Temp\\pip-install-ruvcf595\\spdlog_c72a425b30be4082819d3d73c1eddb44\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ronal\AppData\Local\Temp\pip-record-3ciqrv4c\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\ViperGL\ViperGL\ViperGLEnv\include\site\python3.7\spdlog'
         cwd: C:\Users\ronal\AppData\Local\Temp\pip-install-ruvcf595\spdlog_c72a425b30be4082819d3d73c1eddb44\
    Complete output (15 lines):
    WARNING: The wheel package is not available.
    running install
    running build
    running build_ext
    building 'spdlog' extension
    creating build
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ispdlog/include/ -ID:\ViperGL\ViperGL\ViperGLEnv\lib\site-packages\pybind11\include -ID:\ViperGL\ViperGL\ViperGLEnv\lib\site-packages\pybind11\include -ID:\ViperGL\ViperGL\ViperGLEnv\include "-IC:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tpsrc/pyspdlog.cpp /Fobuild\temp.win-amd64-3.7\Release\src/pyspdlog.obj -std=c++11 -v
    cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
    cl : Command line warning D9002 : ignoring unknown option '-v'
    pyspdlog.cpp
    spdlog/include/spdlog/sinks/syslog_sink.h(16): fatal error C1083: Cannot open include file: 'syslog.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\ViperGL\ViperGL\ViperGLEnv\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ronal\\AppData\\Local\\Temp\\pip-install-ruvcf595\\spdlog_c72a425b30be4082819d3d73c1eddb44\\setup.py'"'"'; __file__='"'"'C:\\Users\\ronal\\AppData\\Local\\Temp\\pip-install-ruvcf595\\spdlog_c72a425b30be4082819d3d73c1eddb44\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ronal\AppData\Local\Temp\pip-record-3ciqrv4c\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\ViperGL\ViperGL\ViperGLEnv\include\site\python3.7\spdlog' Check the logs for full command output.
----- Failed to install 'spdlog' -----`

**Comment by bodgergely** [comment]
Part of the problem is that I have never tried to install (compile) spdlog-python on Windows. I am looking into this issue now.

**Comment by RonaldoAPSD** [comment]
@bodgergely Thanks a bunch! It would be of great help if I could get it running on windows.

**Comment by bodgergely** [comment]
@RonaldoAPSD Can you check if you can do exactly:
`pip install spdlog`
See if you pick it up v2.0.4 from PyPi since I released a new version.
