### ISSUE TITLE
async flush or spdlog::shutdown() equivalent

### ISSUE THREAD

**Issue by yhyu13** [bodgergely/spdlog-python#30]
Hi, 

I am using async logger primarily. From the c++ doc [spdlog flush](https://spdlog.docsforge.com/v1.x/7.flush-policy/), it seems that flush() on async logger returns immediately which I think would not take actual effect. It does suggest using the static method spdlog::shutdown(). Is there a method in spdlog-python that does the same thing? Or is there any way to safely flush all async loggers?

 Thanks~!

**Comment by bodgergely** [comment]
Hi, I am going to look at this now.

**Comment by bodgergely** [comment]
As you can see, back in 2018, when I first implemented spdlog-python I had problems with flush() on async loggers:
https://github.com/bodgergely/spdlog-python/issues/1

**Comment by bodgergely** [comment]
Basically, I was testing now and playing around flush(). I don't really like it to be honest, it does not seem flush reliably for me.
Honestly I am not really actively maintaining this repo, so if you find a neat solution with shutdown(), feel free to raise a PR, I will review it then.

**Comment by yhyu13** [comment]
The implementation of [spdlog::shutdown](https://spdlog.docsforge.com/v1.x/source/include/spdlog/details/registry-inl.h/) internally calls drop_all(). I found you already included [drop_all()](https://github.com/bodgergely/spdlog-python/blob/42e3aa4821be4a2989c15c54f15ddf8e8488ea58/src/pyspdlog.cpp#L655), it worked.

In my case, I think invoking [close()](https://github.com/bodgergely/spdlog-python/blob/42e3aa4821be4a2989c15c54f15ddf8e8488ea58/src/pyspdlog.cpp#L334) method which calls spdlog::drop() internally works better for me since I manage the refernce to each logger, I can just call close() for each one of them before exit.
