### ISSUE TITLE
set_pattern problem

### ISSUE THREAD

**Issue by gkarsai** [bodgergely/spdlog-python#5]
set_pattern() fails as follows:

Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spdlog as spd
>>> l=spd.ConsoleLogger('cons')
>>> l.set_pattern('%v')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: set_pattern(): incompatible function arguments. The following argument types are supported:
    1. (self: spdlog.Logger, arg0: str, arg1: spdlog::pattern_time_type) -> None

Invoked with: <spdlog.ConsoleLogger object at 0x7fcdd00be378>, '%v'
----
Note: environment: Ubuntu 16.04, gcc 5.4.0, Python 3.5.2, pybind11 2.2.1

**Comment by bodgergely** [comment]
@rafalmiel we should look at this.

**Comment by gkarsai** [comment]
The problem appears to be with the second argument - pybind11 does not 'know' that type. As a workaround the python interface may drop it (and the downcall into c++ will always supply a 'local time' value) -- but this is not a solution. Perhaps pattern_time_type should be wrapped as its own pybind class?

**Comment by rafalmiel** [comment]
Thanks for bug report Gabor. You are right, python did not recognised this enum type.
Created a pull request https://github.com/bodgergely/spdlog-python/pull/6

**Comment by gkarsai** [comment]
Thanks - pull request seems to be working (tried set_patter w/o 2nd arg, w/ local and w/ utc as args)

**Comment by rafalmiel** [comment]
Great, I got it merged. Thanks @gkarsai

**Comment by bodgergely** [comment]
thanks both, I was somewhat busy today
