### ISSUE TITLE
spdlog.get() problem?

### ISSUE THREAD

**Issue by gkarsai** [bodgergely/spdlog-python#8]
spdlog.get(name) returns a Logger object belonging to the name. But the real object in the global object list is of a derived type of Logger (e.g. ConsoleLogger). Will pybind construct a python object of the correct type? 
I am getting bad_alloc-s and segv-s when using this method,

**Comment by bodgergely** [comment]
I will look into this issue, thanks for raising it.

**Comment by bodgergely** [comment]
I tested it and I am getting the correct type back.
Let's assume:
`
spdlog.FileLogger("FL", "/tmp/filelog")    # returns spdlog.FileLogger
fl = spdlog.get("FL")     # fl is a spdlog.Logger instance (behind the scenes it is a FileLogger)
fl.info("Hello")   # writes "hello" to file buffer
fl.flush()   # flush file buffer
`
